spring:
  # Configuration datasource pour l'environnement de développement
  datasource:
    url: jdbc:postgresql://localhost:5432/fluxi_dev
    username: fluxi
    password: fluxi
    driver-class-name: org.postgresql.Driver
  
  # Configuration JPA pour dev - logs SQL activés
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
  
  # Configuration Flyway pour dev
  flyway:
    clean-disabled: false  # Permet flyway:clean en dev

# Logging plus verbeux en développement
logging:
  level:
    com.fluxi.backend: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.springframework.transaction: DEBUG
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"

# Configuration pour le rechargement automatique
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/resources
    livereload:
      enabled: true

# Configuration pour l'environnement de développement