spring:
  application:
    name: fluxi-backend
  profiles:
    active: dev
  
  # Configuration de base de données
  datasource:
    hikari:
      maximum-pool-size: 20
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000
  
  # Configuration JPA/Hibernate
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        show_sql: false
        jdbc:
          batch_size: 25
          order_inserts: true
          order_updates: true
        cache:
          use_second_level_cache: false
        connection:
          provider_disables_autocommit: false
  
  # Configuration Flyway
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
  
  # Configuration RabbitMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# Configuration de logging
logging:
  level:
    com.fluxi.backend: INFO
    org.springframework.security: WARN
    org.hibernate: WARN
    com.zaxxer.hikari: WARN

# Configuration management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,flyway
  endpoint:
    health:
      show-details: when-authorized
